name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # استخدم نسخة Node.js المناسبة لك

    - name: Install dependencies
      run: npm install

    - name: Run the bot
      run: node index.js  # أو الملف الذي يحتوي على البوت الخاص بك
